### ISSUE TITLE
Running the first example

### ISSUE THREAD

**Issue by mintyPT** [hofstadter-io/hof-docs#15]
When I run

```hof gen ./examples```

I get this

```
Errors while loading Cue entrypoints:  [./examples]
import failed: cannot find package "hof.io/docs/first-example/gen":
    ./examples/gen.cue:4:2
```

I understand what this means but since I'm no go programmer, I'm not familiar with tooling. How to solve this?

**Comment by verdverm** [comment]
Did you happen to run the following and get the same error?

```
$ hof gen --init hof.io/docs/first-example
Initializing: hof.io/docs/first-example in pkg first-exampleparse: expected ',', found '-'
```

I can see a few typos and mis-instructions

This is a CUE error, before we reach the Go code created by the first-example and try to run that. So this error is being thrown by hof, but ultimately coming from CUE, because I have misaligned the module & package identifiers, I suspect

---

Can you run the following and paste it back here?

```
tree -I cue.mod
cat cue.mods
```

or if you have a link to a repository, or can tar it up and share it, that could be better

**Comment by mintyPT** [comment]
Don't think so. I generated the initial scaffolding without issues. 

Here's the info you asked

```
tree -I cue.mod
.
├── creators
├── cue.mods
├── cue.sums
├── examples
│   ├── gen.cue
│   └── server.cue
├── first-example.cue
├── generators
│   └── server.cue
├── partials
│   └── handler.go
├── schema
│   └── server.cue
├── statics
└── templates
    ├── go.mod
    ├── middleware.go
    ├── route.go
    ├── router.go
    └── server.go
```

```
cat cue.mods


module hof.io/docs/first-example

cue v0.4.3

require (
	github.com/hofstadter-io/hof v0.6.7
)
```

**Comment by mintyPT** [comment]
Btw, I changed the directory name to `firstexample` and replaced every mention of `first-example` by `firstexample`. The result:

```
hof gen ./examples


Errors while loading Cue entrypoints:  [./examples]
import failed: cannot find package "hof.io/docs/firstexample/gen":
    ./examples/gen.cue:4:2

**Comment by verdverm** [comment]
ah, I see the issue

`gen` vs `generators`

`import failed: cannot find package "hof.io/docs/first-example/gen"`

vs

```
tree -I cue.mod
...
├── generators
│   └── server.cue
```

They should be consistent. You can fix this by renaming the directory `generators` to `gen`

```
mv generators gen
```

**Comment by verdverm** [comment]
btw, I've fixed a couple of issues with the getting-started section, the issue here and some deprecated usage. Changes are now live

- `#HofGenerator` -> `#Generator`
- `#HofGeneratorFile` -> `#File`

**Comment by mintyPT** [comment]
Ok, now ot works!

**Comment by verdverm** [comment]
Nice! Glad to hear it and thank you for helping make hof better!
