### ISSUE TITLE
Code blocks have a "copy" button that does not work in Safari

### ISSUE THREAD

**Issue by halostatue** [hofstadter-io/hof-docs#3]
<img width="1016" alt="CleanShot 2022-06-06 at 16 26 38@2x" src="https://user-images.githubusercontent.com/11361/172242940-1460e9ad-9bc0-4fdd-9613-7360c1d2ad71.png">

I’m using Safari 15.5

The buttons respond, but do not copy the contents.

**Comment by verdverm** [comment]
Do the browser console logs have any entries?

**Comment by halostatue** [comment]
They don’t appear to be related to the click action.

```
Content blocker prevented frame displaying https://docs.hofstadter.io/first-example/simple-server/setup/ from loading a resource from https://www.googletagmanager.com/gtag/js?id=UA-103579574-2
```

After reload without a content blocker, I get:

```
Refused to connect to https://stats.g.doubleclick.net/j/collect?t=dc&aip=1&_r=3&v=1&_v=j96&tid=UA-103579574-2&cid=664440607.1654547161&jid=1530600378&gjid=1243794365&_gid=997812852.1654634269&_u=YADAAUAAAAAAAC~&z=965897652 because it does not appear in the connect-src directive of the Content Security Policy.
```

The generated bundle.js file appears to be blank, however.

**Comment by verdverm** [comment]
oof, it seems that it's broken in all the places...

Does the copy work for you here: https://cuetorials.com/first-steps/validate-configuration/

**Comment by verdverm** [comment]
@halostatue is the `bundle.js` the full file name or does it have a long hash suffix like this:

![image](https://user-images.githubusercontent.com/1390600/172488810-83b126a3-cfd6-4078-ba04-1ce75e04f969.png)

**Comment by halostatue** [comment]
It’s the hashed one (`bundle.dad0….js` exactly). It looks like it loaded this time (now that I looked in the network tab). Putting a breakpoint on the click handler tells me…nothing useful.

<img width="363" alt="CleanShot 2022-06-07 at 17 54 21@2x" src="https://user-images.githubusercontent.com/11361/172489642-771283ef-fa06-4cbb-bc01-12fd9b0828a5.png"/>

<img width="323" alt="CleanShot 2022-06-07 at 17 54 32@2x" src="https://user-images.githubusercontent.com/11361/172489659-6b417056-12af-4fef-8580-4c62621da21a.png">

<img width="324" alt="CleanShot 2022-06-07 at 17 55 17@2x" src="https://user-images.githubusercontent.com/11361/172489665-81201be5-d790-4d66-a076-cb451afc55b8.png">

**Comment by verdverm** [comment]
fixed in https://github.com/hofstadter-io/hof-docs/commit/fcc175d16bc888015a90e40691e1d178ddbed7e6

**Comment by verdverm** [comment]
@halostatue is copy working now?

**Comment by halostatue** [comment]
Thanks for the quick response!
